import type { CoreRulesDocument } from '@/lib/rules/core-rules-document'
import type { ExtractedCoreRulesFamily } from '../rules-document-family.ts'

const GENERATED_HEADER = '// Generated by pnpm rules:generate. Do not edit.\n\n'
export type CoreRulesArtifacts = {
	artifacts: Map<string, string>
	transcripts: Map<string, string>
	summary: { versions: number; transcripts: number; current: string }
}

function exportName(version: string) {
	return `PDF_CORE_RULES_${version.replace('.', '_')}`
}

function outputFilename(version: string) {
	return `v${version.replace('.', '-')}.ts`
}

function serializeVersion(document: CoreRulesDocument, version: string) {
	return `${GENERATED_HEADER}import type { CoreRulesDocument } from '@/lib/rules/core-rules-document'\n\n// oxfmt-ignore\nexport const ${exportName(version)}: CoreRulesDocument = ${JSON.stringify(document, null, 2)}\n`
}

function serializeIndex(versions: readonly string[], current: string, versionNames: Record<string, string>) {
	const imports = versions
		.map(
			(version) =>
				`import { ${exportName(version)} } from '@/generated/core-rules/v${version.replace('.', '-')}'`,
		)
		.join('\n')
	const entries = versions
		.map((version) => `\t${JSON.stringify(version)}: ${exportName(version)},`)
		.join('\n')
	const nameEntries = Object.keys(versionNames)
		.map((version) => `\t${JSON.stringify(version)}: ${JSON.stringify(versionNames[version])},`)
		.join('\n')

	return `${GENERATED_HEADER}${imports}\nimport type { CoreRulesDocument } from '@/lib/rules/core-rules-document'\n\nexport const CURRENT_PDF_CORE_RULES_VERSION = ${JSON.stringify(current)}\n\nexport const PDF_CORE_RULES_VERSIONS: Record<string, CoreRulesDocument> = {\n${entries}\n}\n\nexport const PDF_CORE_RULES_VERSION_NAMES: Record<string, string> = {\n${nameEntries}\n}\n`
}

export function prepareCoreRulesArtifacts(extracted: ExtractedCoreRulesFamily): CoreRulesArtifacts {
	const versions = extracted.versions.map(({ registeredVersion }) => registeredVersion.version)
	const versionNames = Object.fromEntries(
		extracted.versions.flatMap(({ registeredVersion: { version, name } }) =>
			name === undefined ? [] : [[version, name]],
		),
	)
	const artifacts = new Map<string, string>()
	const transcripts = new Map<string, string>()

	for (const { registeredVersion, document, transcript } of extracted.versions) {
		const { version } = registeredVersion
		artifacts.set(outputFilename(version), serializeVersion(document, version))
		if (transcript !== null) transcripts.set(`CR-v${version}.txt`, transcript)
	}

	const current = extracted.currentVersion.registeredVersion.version
	artifacts.set('index.ts', serializeIndex(versions, current, versionNames))
	return {
		artifacts,
		transcripts,
		summary: {
			versions: versions.length,
			transcripts: transcripts.size,
			current,
		},
	}
}
