import { mkdir, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { CoreRulesDocument, CoreRulesSection, RuleNode, RulesHeading } from '@/features/core-rules/types'
import { normalizeRulesDate } from '../rules-date.ts'
import { inspectPdf, type CoreRulesReport } from './inspect.ts'

const PROJECT_DIRECTORY = join(import.meta.dirname, '..', '..')
const DEFAULT_SOURCES_DIRECTORY = join(PROJECT_DIRECTORY, 'sources')
const DEFAULT_OUTPUT_DIRECTORY = join(PROJECT_DIRECTORY, 'src', 'generated', 'core-rules')
const GENERATED_HEADER = '// Generated by pnpm rules:generate. Do not edit.\n\n'
const VERSION = /^1\.(\d+)$/u

type CoreRulesVersionMetadata = { name?: string }
type CoreRulesManifest = {
	current: string
	versions: Record<string, CoreRulesVersionMetadata>
	versionNames: Record<string, string>
}

export type CoreRulesArtifacts = {
	artifacts: Map<string, string>
	referenceVersions: { version: string; name: string | undefined; lastUpdated: string }[]
	transcripts: Map<string, string>
	summary: { versions: number; transcripts: number; current: string }
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === 'object' && value !== null
}

function readManifest(manifest: unknown): CoreRulesManifest {
	if (!manifest || typeof manifest !== 'object') throw new TypeError('expected a manifest object')
	if (!('coreRules' in manifest)) throw new TypeError('expected coreRules metadata')
	const coreRules = manifest.coreRules
	if (!isRecord(coreRules)) throw new TypeError('expected coreRules metadata')
	if (typeof coreRules.current !== 'string') throw new TypeError('expected coreRules.current')
	if (!isRecord(coreRules.versions)) {
		throw new TypeError('expected coreRules.versions')
	}

	const versions: Record<string, CoreRulesVersionMetadata> = {}
	for (const [version, metadata] of Object.entries(coreRules.versions)) {
		if (!VERSION.test(version)) throw new TypeError(`invalid Core Rules version ${version}`)
		if (!isRecord(metadata)) {
			throw new TypeError(`expected metadata for Core Rules ${version}`)
		}
		if (metadata.name !== undefined && (typeof metadata.name !== 'string' || !metadata.name)) {
			throw new TypeError(`expected a non-empty name for Core Rules ${version}`)
		}
		versions[version] = { name: typeof metadata.name === 'string' ? metadata.name : undefined }
	}

	if (!versions[coreRules.current]) {
		throw new TypeError(`current Core Rules version ${coreRules.current} is not defined`)
	}
	return {
		current: coreRules.current,
		versions,
		versionNames: Object.fromEntries(
			Object.entries(versions)
				.filter(([, metadata]) => metadata.name)
				.map(([version, metadata]) => [version, metadata.name as string]),
		),
	}
}

function compareVersions(left: string, right: string) {
	return left.localeCompare(right, 'en', { numeric: true })
}

function exportName(version: string) {
	return `PDF_CORE_RULES_${version.replace('.', '_')}`
}

function outputFilename(version: string) {
	return `v${version.replace('.', '-')}.ts`
}

function runtimeHeading(heading: { source: { sequence: number }; id: string; text: string }): RulesHeading {
	return { sequence: heading.source.sequence, id: heading.id, text: heading.text }
}

function runtimeRules(rules: CoreRulesReport['structured']['sections'][number]['preamble']): RuleNode[] {
	return rules.map((rule) => ({
		sequence: rule.source.sequence,
		id: rule.id,
		content: rule.content,
		children: runtimeRules(rule.children),
	}))
}

function runtimeSections(sections: CoreRulesReport['structured']['sections']): CoreRulesSection[] {
	return sections.map((section) => ({
		heading: runtimeHeading(section.heading),
		preamble: runtimeRules(section.preamble),
		subsections: section.subsections.map((subsection) => ({
			heading: runtimeHeading(subsection.heading),
			rules: runtimeRules(subsection.rules),
		})),
	}))
}

function validateReport(report: CoreRulesReport) {
	if (!report.title) throw new Error(`${report.file}: missing document title`)
	const lastUpdated = normalizeRulesDate(report.lastUpdated, `${report.file}: Last Updated`)
	if (report.physicalLineCount !== report.assignedPhysicalLines + report.unassignedLines.length) {
		throw new Error(`${report.file}: physical line assignment is incomplete`)
	}
	if (
		report.unassignedLines.length !== 2 ||
		report.unassignedLines[0]?.text !== report.title ||
		!report.unassignedLines[1]?.text.startsWith('Last Updated:')
	) {
		throw new Error(`${report.file}: unexpected content before the first rule block`)
	}
	const structuralErrors = report.structured.diagnostics.filter(({ severity }) => severity === 'error')
	if (structuralErrors.length > 0) {
		throw new Error(`${report.file}: ${structuralErrors.length} structural errors`)
	}
	return lastUpdated
}

function serializeVersion(document: CoreRulesDocument, version: string) {
	return `${GENERATED_HEADER}import type { CoreRulesDocument } from '@/features/core-rules/types'\n\n// oxfmt-ignore\nexport const ${exportName(version)}: CoreRulesDocument = ${JSON.stringify(document, null, 2)}\n`
}

export function serializeCoreRulesTranscript(report: CoreRulesReport) {
	const lines = [report.title, `Last Updated: ${report.lastUpdated}`]
	for (const record of report.records) {
		const [firstLine, ...continuationLines] = record.sourceLines
		lines.push(
			`${record.label}${firstLine?.text ? ` ${firstLine.text}` : ''}`,
			...continuationLines.map(({ text }) => text),
		)
	}
	return `${lines.join('\n')}\n`
}

function serializeIndex(versions: readonly string[], current: string, versionNames: Record<string, string>) {
	const imports = versions
		.map(
			(version) =>
				`import { ${exportName(version)} } from '@/generated/core-rules/v${version.replace('.', '-')}'`,
		)
		.join('\n')
	const entries = versions
		.map((version) => `\t${JSON.stringify(version)}: ${exportName(version)},`)
		.join('\n')
	const nameEntries = Object.keys(versionNames)
		.toSorted(compareVersions)
		.map((version) => `\t${JSON.stringify(version)}: ${JSON.stringify(versionNames[version])},`)
		.join('\n')

	return `${GENERATED_HEADER}${imports}\nimport { buildCoreRulesLookup } from '@/features/core-rules/lookup'\nimport type { CoreRulesDocument } from '@/features/core-rules/types'\n\nexport const CURRENT_PDF_CORE_RULES_VERSION = ${JSON.stringify(current)}\n\nexport const PDF_CORE_RULES_VERSIONS: Record<string, CoreRulesDocument> = {\n${entries}\n}\n\nexport const PDF_CORE_RULES_VERSION_NAMES: Record<string, string> = {\n${nameEntries}\n}\n\nexport const PDF_CORE_RULES_BY_ID: Record<string, Map<string, string>> = Object.fromEntries(\n\tObject.entries(PDF_CORE_RULES_VERSIONS).map(([version, document]) => [\n\t\tversion,\n\t\tbuildCoreRulesLookup(document),\n\t]),\n)\n`
}

export async function prepareCoreRules(
	rawManifest: unknown,
	{ sourcesDirectory = DEFAULT_SOURCES_DIRECTORY }: { sourcesDirectory?: string } = {},
): Promise<CoreRulesArtifacts> {
	const manifest = readManifest(rawManifest)
	const versions = Object.keys(manifest.versions).toSorted(compareVersions)
	const artifacts = new Map<string, string>()
	const transcripts = new Map<string, string>()
	const referenceVersions: CoreRulesArtifacts['referenceVersions'] = []

	for (const version of versions) {
		const sourcePath = join(sourcesDirectory, `CR-v${version}.pdf`)
		// Large PDFs are intentionally processed sequentially to cap memory usage.
		// oxlint-disable-next-line no-await-in-loop
		const report = await inspectPdf(sourcePath)
		const lastUpdated = validateReport(report)
		const document: CoreRulesDocument = {
			schemaVersion: 3,
			version,
			sections: runtimeSections(report.structured.sections),
		}
		artifacts.set(outputFilename(version), serializeVersion(document, version))
		referenceVersions.push({ version, name: manifest.versionNames[version], lastUpdated })
		if (manifest.versionNames[version]) {
			transcripts.set(`CR-v${version}.txt`, serializeCoreRulesTranscript({ ...report, lastUpdated }))
		}
	}

	artifacts.set('index.ts', serializeIndex(versions, manifest.current, manifest.versionNames))
	return {
		artifacts,
		referenceVersions,
		transcripts,
		summary: { versions: versions.length, transcripts: transcripts.size, current: manifest.current },
	}
}

export async function publishCoreRules(
	{ artifacts, transcripts }: Pick<CoreRulesArtifacts, 'artifacts' | 'transcripts'>,
	{
		outputDirectory = DEFAULT_OUTPUT_DIRECTORY,
		transcriptOutputDirectory = DEFAULT_SOURCES_DIRECTORY,
	}: { outputDirectory?: string; transcriptOutputDirectory?: string } = {},
) {
	await rm(outputDirectory, { recursive: true, force: true })
	await mkdir(outputDirectory, { recursive: true })
	await Promise.all(
		[...artifacts].map(([filename, contents]) => writeFile(join(outputDirectory, filename), contents)),
	)
	await mkdir(transcriptOutputDirectory, { recursive: true })
	await Promise.all(
		[...transcripts].map(([filename, contents]) =>
			writeFile(join(transcriptOutputDirectory, filename), contents),
		),
	)
}
