// Generates the TypeScript datasets consumed by the site from committed rules sources.

import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { parseCr } from './parse-cr.mjs'
import { parseTournamentRulesFile } from './parse-tr.mjs'
import { serializeRuleRecords } from './rules-parser-utils.mjs'

const ROOT_DIRECTORY = import.meta.dirname
const DEFAULT_SOURCES_DIRECTORY = join(ROOT_DIRECTORY, '..', 'sources')
const DEFAULT_OUTPUT_DIRECTORY = join(ROOT_DIRECTORY, '..', 'src', 'generated', 'rules')
const GENERATED_HEADER = '// Generated by pnpm rules:generate. Do not edit.\n\n'
const CORE_SOURCE_FILENAME = /^CR-v(\d+\.\d+)\.txt$/u
const TOURNAMENT_SOURCE_FILENAME = /^Tournament-Rules-(\d{4}-\d{2}-\d{2})\.txt$/u

function readManifest(rawManifest) {
	const manifest = JSON.parse(rawManifest)
	if (!manifest || typeof manifest !== 'object') {
		throw new TypeError('rules-manifest.json: expected an object')
	}

	const coreRules = manifest.coreRules
	if (!coreRules || typeof coreRules !== 'object') {
		throw new TypeError('rules-manifest.json: expected coreRules metadata')
	}
	if (typeof coreRules.current !== 'string') {
		throw new TypeError('rules-manifest.json: expected coreRules.current')
	}
	if (!coreRules.versions || typeof coreRules.versions !== 'object') {
		throw new TypeError('rules-manifest.json: expected coreRules.versions')
	}

	for (const [version, metadata] of Object.entries(coreRules.versions)) {
		if (!CORE_SOURCE_FILENAME.test(`CR-v${version}.txt`)) {
			throw new TypeError(`rules-manifest.json: invalid Core Rules version ${version}`)
		}
		if (!metadata || typeof metadata !== 'object' || typeof metadata.name !== 'string' || !metadata.name) {
			throw new TypeError(`rules-manifest.json: expected a name for Core Rules ${version}`)
		}
	}

	const tournamentRules = manifest.tournamentRules
	if (
		!tournamentRules ||
		typeof tournamentRules !== 'object' ||
		typeof tournamentRules.current !== 'string'
	) {
		throw new TypeError('rules-manifest.json: expected tournamentRules.current')
	}

	return manifest
}

function compareVersions(left, right) {
	return left.localeCompare(right, 'en', { numeric: true })
}

function dataExportName(prefix, version) {
	return `${prefix}_${version.replaceAll(/[.-]/gu, '_')}`
}

function serializeCoreRulesIndex(versions, manifest) {
	const imports = versions
		.map(
			({ version }) =>
				`import { ${dataExportName('RULES', version)} } from '@/generated/rules/core-rules/v${version.replace('.', '-')}'`,
		)
		.join('\n')
	const entries = versions
		.map(({ version, lastUpdated }) => {
			const name = manifest.coreRules.versions[version].name
			return `\t${JSON.stringify(version)}: { version: ${JSON.stringify(version)}, name: ${JSON.stringify(name)}, lastUpdated: ${JSON.stringify(lastUpdated)}, rules: ${dataExportName('RULES', version)} },`
		})
		.join('\n')

	return `${GENERATED_HEADER}${imports}\nimport type { RuleRecord } from '@/components/rules/types'\n\nexport type CrdVersion = {\n\tversion: string\n\tname: string\n\tlastUpdated: string\n\trules: RuleRecord[]\n}\n\nexport const CURRENT_CRD_VERSION = ${JSON.stringify(manifest.coreRules.current)}\n\nexport const CRD_VERSIONS: Record<string, CrdVersion> = {\n${entries}\n}\n\nexport const RULES_BY_ID: Record<string, Map<string, string[]>> = Object.fromEntries(\n\tObject.entries(CRD_VERSIONS).map(([version, crd]) => [\n\t\tversion,\n\t\tnew Map(crd.rules.map((rule) => [rule.id, rule.lines])),\n\t]),\n)\n`
}

function serializeTournamentRulesIndex(versions, manifest) {
	const imports = versions
		.map(
			({ version }) =>
				`import { ${dataExportName('TOURNAMENT_RULES', version)} } from '@/generated/rules/tournament-rules/v${version}'`,
		)
		.join('\n')
	const entries = versions
		.map(
			({ version }) =>
				`\t${JSON.stringify(version)}: { version: ${JSON.stringify(version)}, rules: ${dataExportName('TOURNAMENT_RULES', version)} },`,
		)
		.join('\n')

	return `${GENERATED_HEADER}${imports}\nimport type { RuleRecord } from '@/components/rules/types'\n\nexport type TournamentRulesVersion = {\n\tversion: string\n\trules: RuleRecord[]\n}\n\nexport const CURRENT_TOURNAMENT_RULES_VERSION = ${JSON.stringify(manifest.tournamentRules.current)}\n\nexport const TOURNAMENT_RULES_VERSIONS: Record<string, TournamentRulesVersion> = {\n${entries}\n}\n`
}

export async function generateRules({
	sourcesDirectory = DEFAULT_SOURCES_DIRECTORY,
	outputDirectory = DEFAULT_OUTPUT_DIRECTORY,
	manifestPath = join(sourcesDirectory, 'rules-manifest.json'),
} = {}) {
	const manifest = readManifest(await readFile(manifestPath, 'utf8'))
	const sourceFilenames = await readdir(sourcesDirectory)
	const artifacts = new Map()

	const coreSourceFilenames = sourceFilenames
		.filter((filename) => filename.startsWith('CR-v') && filename.endsWith('.txt'))
		.toSorted()
	if (coreSourceFilenames.length === 0) throw new Error('no Core Rules sources found')

	const coreVersions = await Promise.all(
		coreSourceFilenames.map(async (filename) => {
			const filenameMatch = filename.match(CORE_SOURCE_FILENAME)
			if (!filenameMatch) throw new Error(`${filename}: expected CR-vX.Y.txt`)
			const version = filenameMatch[1]
			if (!manifest.coreRules.versions[version]) {
				throw new Error(`${filename}: missing Core Rules metadata for ${version}`)
			}

			const { lastUpdated, rules } = parseCr(await readFile(join(sourcesDirectory, filename), 'utf8'))
			const exportName = dataExportName('RULES', version)
			return {
				version,
				lastUpdated,
				relativePath: join('core-rules', `v${version.replace('.', '-')}.ts`),
				contents: GENERATED_HEADER + serializeRuleRecords(rules, exportName),
			}
		}),
	)
	coreVersions.sort((left, right) => compareVersions(left.version, right.version))
	for (const { relativePath, contents } of coreVersions) artifacts.set(relativePath, contents)

	for (const version of Object.keys(manifest.coreRules.versions)) {
		if (!coreVersions.some((entry) => entry.version === version)) {
			throw new Error(`rules-manifest.json: Core Rules ${version} has no matching source`)
		}
	}
	if (!manifest.coreRules.versions[manifest.coreRules.current]) {
		throw new Error(`rules-manifest.json: current Core Rules ${manifest.coreRules.current} is not defined`)
	}

	const tournamentSourceFilenames = sourceFilenames
		.filter((filename) => filename.startsWith('Tournament-Rules-') && filename.endsWith('.txt'))
		.toSorted()
	if (tournamentSourceFilenames.length === 0) throw new Error('no Tournament Rules sources found')

	const tournamentVersions = []
	for (const filename of tournamentSourceFilenames) {
		if (!TOURNAMENT_SOURCE_FILENAME.test(filename)) {
			throw new Error(`${filename}: expected Tournament-Rules-YYYY-MM-DD.txt`)
		}
		const { lastUpdated: version, rules } = parseTournamentRulesFile(join(sourcesDirectory, filename))
		const exportName = dataExportName('TOURNAMENT_RULES', version)
		artifacts.set(
			join('tournament-rules', `v${version}.ts`),
			GENERATED_HEADER + serializeRuleRecords(rules, exportName),
		)
		tournamentVersions.push({ version })
	}
	tournamentVersions.sort((left, right) => compareVersions(left.version, right.version))

	if (!tournamentVersions.some((entry) => entry.version === manifest.tournamentRules.current)) {
		throw new Error(
			`rules-manifest.json: current Tournament Rules ${manifest.tournamentRules.current} has no matching source`,
		)
	}

	artifacts.set('core-rules/index.ts', serializeCoreRulesIndex(coreVersions, manifest))
	artifacts.set('tournament-rules/index.ts', serializeTournamentRulesIndex(tournamentVersions, manifest))

	await rm(outputDirectory, { recursive: true, force: true })
	await Promise.all(
		[...artifacts].map(async ([relativePath, contents]) => {
			const outputPath = join(outputDirectory, relativePath)
			await mkdir(dirname(outputPath), { recursive: true })
			await writeFile(outputPath, contents)
		}),
	)

	return { coreRules: coreVersions.length, tournamentRules: tournamentVersions.length }
}

if (process.argv[1] === import.meta.filename) {
	const generated = await generateRules()
	console.log(
		`Generated ${generated.coreRules} Core Rules and ${generated.tournamentRules} Tournament Rules versions.`,
	)
}
