import { mkdir, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { TournamentRulesDocument, TournamentRulesSection } from '@/features/tournament-rules/types'
import { normalizeRulesDate } from '../rules-date.ts'
import type { TournamentRulesFamily } from '../rules-manifest.ts'
import { inspectTournamentPdf, type TournamentPdfReport, type TournamentRow } from './inspect.ts'
import { structureTournamentRows, type TournamentStructureDiagnostic } from './structure.ts'

const PROJECT_DIRECTORY = join(import.meta.dirname, '..', '..')
const DEFAULT_SOURCES_DIRECTORY = join(PROJECT_DIRECTORY, 'sources')
const DEFAULT_OUTPUT_DIRECTORY = join(PROJECT_DIRECTORY, 'src', 'generated', 'tournament-rules')
const TITLE = 'Riftbound Tournament Rules'
const GENERATED_HEADER = '// Generated by pnpm rules:generate. Do not edit.\n\n'

type RuntimeArtifact = { version: string; document: TournamentRulesDocument }

export type PreparedTournamentRules = {
	artifacts: Map<string, string>
	referenceVersions: { version: string; lastUpdated: string }[]
	transcripts: Map<string, string>
	summary: { current: string; versions: number; transcripts: number }
}

function completeRowText(row: TournamentRow): string {
	return `${row.rawLabel}${row.text ? ` ${row.text}` : ''}`.trim()
}

function validateReport(report: TournamentPdfReport, version: string): string {
	const lastUpdated = normalizeRulesDate(report.lastUpdated, `${report.file}: Last Updated`)
	if (report.version !== version)
		throw new Error(`${report.file}: filename does not identify version ${version}`)
	if (lastUpdated !== version) {
		throw new Error(
			`${report.file}: Last Updated ${report.lastUpdated || '(missing)'} does not match ${version}`,
		)
	}
	if (report.title !== TITLE) throw new Error(`${report.file}: unexpected document title ${report.title}`)
	if (report.rows.length === 0) throw new Error(`${report.file}: no table rows found`)
	if (report.rows.some(({ kind, id }) => kind !== 'rule' && !id)) {
		throw new Error(`${report.file}: heading without an ID`)
	}

	for (const row of report.rows.filter(({ active }) => !active)) {
		if (row.removedText !== completeRowText(row)) {
			throw new Error(`${report.file}: partial strikeout on page ${row.page} requires manual review`)
		}
	}
	return lastUpdated
}

function runtimeDocument(
	report: TournamentPdfReport,
	sections: TournamentRulesSection[],
): TournamentRulesDocument {
	return { schemaVersion: 1, version: report.version!, sections }
}

function warnAboutStructure(file: string, diagnostics: TournamentStructureDiagnostic[]): void {
	if (diagnostics.length === 0) return
	const counts = new Map<TournamentStructureDiagnostic['code'], number>()
	for (const { code } of diagnostics) counts.set(code, (counts.get(code) ?? 0) + 1)
	const summary = [...counts]
		.toSorted(([left], [right]) => left.localeCompare(right))
		.map(([code, count]) => `${code}: ${count}`)
		.join(', ')
	console.warn(`${file}: preserved structural anomalies (${summary})`)
}

function serializeTranscript(report: TournamentPdfReport): string {
	const lines = [report.title, `Last Updated: ${report.lastUpdated}`]
	for (const row of report.rows.filter(({ active }) => active)) {
		lines.push(`${row.label ?? row.rawLabel}${row.text ? ` ${row.text}` : ''}`.trim())
	}
	return `${lines.join('\n')}\n`
}

function documentExportName(version: string): string {
	return `PDF_TOURNAMENT_RULES_${version.replaceAll('-', '_')}`
}

function versionFilename(version: string): string {
	return `v${version}.ts`
}

function serializeRuntimeVersion(document: TournamentRulesDocument): string {
	return `${GENERATED_HEADER}import type { TournamentRulesDocument } from '@/features/tournament-rules/types'\n\n// oxfmt-ignore\nexport const ${documentExportName(document.version)}: TournamentRulesDocument = ${JSON.stringify(document, null, 2)}\n`
}

function serializeRuntimeIndex(artifacts: RuntimeArtifact[], current: string): string {
	const imports = artifacts
		.map(
			({ version }) =>
				`import { ${documentExportName(version)} } from '@/generated/tournament-rules/v${version}'`,
		)
		.join('\n')
	const documentEntries = artifacts
		.map(({ version }) => `\t${JSON.stringify(version)}: ${documentExportName(version)},`)
		.join('\n')

	return `${GENERATED_HEADER}${imports}\nimport type { TournamentRulesDocument } from '@/features/tournament-rules/types'\n\nexport const CURRENT_PDF_TOURNAMENT_RULES_VERSION = ${JSON.stringify(current)}\n\nexport const PDF_TOURNAMENT_RULES_DOCUMENTS: Record<string, TournamentRulesDocument> = {\n${documentEntries}\n}\n`
}

export async function prepareTournamentRules(
	manifest: TournamentRulesFamily,
	{ sourcesDirectory = DEFAULT_SOURCES_DIRECTORY }: { sourcesDirectory?: string } = {},
): Promise<PreparedTournamentRules> {
	const documents: RuntimeArtifact[] = []
	const artifacts = new Map<string, string>()
	const transcripts = new Map<string, string>()
	const referenceVersions: { version: string; lastUpdated: string }[] = []

	for (const { version } of manifest.registeredVersions) {
		const sourcePath = join(sourcesDirectory, `Tournament-Rules-${version}.pdf`)
		// Large PDFs are intentionally processed sequentially to cap memory use.
		// oxlint-disable-next-line no-await-in-loop
		const report = await inspectTournamentPdf(sourcePath)
		const lastUpdated = validateReport(report, version)
		let structured: ReturnType<typeof structureTournamentRows>
		try {
			structured = structureTournamentRows(report.rows)
		} catch (cause) {
			throw new Error(`${report.file}: Tournament Rules structuring failed`, { cause })
		}
		const { sections, diagnostics } = structured
		warnAboutStructure(report.file, diagnostics)
		const document = runtimeDocument(report, sections)
		documents.push({ version, document })
		referenceVersions.push({ version, lastUpdated })
		artifacts.set(versionFilename(version), serializeRuntimeVersion(document))
		transcripts.set(`Tournament-Rules-${version}.txt`, serializeTranscript({ ...report, lastUpdated }))
	}

	artifacts.set('index.ts', serializeRuntimeIndex(documents, manifest.currentVersion.version))
	return {
		artifacts,
		referenceVersions,
		transcripts,
		summary: {
			current: manifest.currentVersion.version,
			versions: documents.length,
			transcripts: transcripts.size,
		},
	}
}

export async function publishTournamentRules(
	{ artifacts, transcripts }: Pick<PreparedTournamentRules, 'artifacts' | 'transcripts'>,
	{
		outputDirectory = DEFAULT_OUTPUT_DIRECTORY,
		transcriptOutputDirectory = DEFAULT_SOURCES_DIRECTORY,
	}: { outputDirectory?: string; transcriptOutputDirectory?: string } = {},
): Promise<void> {
	await rm(outputDirectory, { recursive: true, force: true })
	await mkdir(outputDirectory, { recursive: true })
	await Promise.all(
		[...artifacts].map(([filename, contents]) => writeFile(join(outputDirectory, filename), contents)),
	)
	await mkdir(transcriptOutputDirectory, { recursive: true })
	await Promise.all(
		[...transcripts].map(([filename, contents]) =>
			writeFile(join(transcriptOutputDirectory, filename), contents),
		),
	)
}
