import { tournamentRulesConventions } from '@/lib/rules/document-family-conventions'
import type { TournamentRulesDocument } from '@/lib/rules/tournament-rules-document'
import type { ExtractedTournamentRulesFamily } from '../rules-document-family'

const GENERATED_HEADER = '// Generated by pnpm rules:generate. Do not edit.\n\n'

type RuntimeArtifact = { version: string; document: TournamentRulesDocument }

export type PreparedTournamentRules = {
	artifacts: Map<string, string>
	transcripts: Map<string, string>
	summary: { current: string; versions: number; transcripts: number }
}

function serializeRuntimeVersion(document: TournamentRulesDocument): string {
	const exportName = tournamentRulesConventions.version(document.version).generated.exportName
	return `${GENERATED_HEADER}import type { TournamentRulesDocument } from '@/lib/rules/tournament-rules-document'\n\n// oxfmt-ignore\nexport const ${exportName}: TournamentRulesDocument = ${JSON.stringify(document, null, 2)}\n`
}

function serializeRuntimeIndex(artifacts: RuntimeArtifact[], current: string): string {
	const imports = artifacts
		.map(({ version }) => {
			const generated = tournamentRulesConventions.version(version).generated
			return `import { ${generated.exportName} } from '${generated.moduleSpecifier}'`
		})
		.join('\n')
	const documentEntries = artifacts
		.map(({ version }) => {
			const exportName = tournamentRulesConventions.version(version).generated.exportName
			return `\t${JSON.stringify(version)}: ${exportName},`
		})
		.join('\n')

	const { currentVersionExport, documentsExport } = tournamentRulesConventions.generated
	return `${GENERATED_HEADER}${imports}\nimport type { TournamentRulesDocument } from '@/lib/rules/tournament-rules-document'\n\nexport const ${currentVersionExport} = ${JSON.stringify(current)}\n\nexport const ${documentsExport}: Record<string, TournamentRulesDocument> = {\n${documentEntries}\n}\n`
}

export function prepareTournamentRulesArtifacts(
	extracted: ExtractedTournamentRulesFamily,
): PreparedTournamentRules {
	const documents: RuntimeArtifact[] = []
	const artifacts = new Map<string, string>()
	const transcripts = new Map<string, string>()

	for (const {
		registeredVersion: { version },
		document,
		transcript,
	} of extracted.versions) {
		const conventions = tournamentRulesConventions.version(version)
		documents.push({ version, document })
		artifacts.set(conventions.generated.filename, serializeRuntimeVersion(document))
		transcripts.set(conventions.source.transcriptFilename, transcript)
	}

	const current = extracted.currentVersion.registeredVersion.version
	artifacts.set('index.ts', serializeRuntimeIndex(documents, current))
	return {
		artifacts,
		transcripts,
		summary: {
			current,
			versions: documents.length,
			transcripts: transcripts.size,
		},
	}
}
