import type { TournamentRulesDocument } from '@/lib/rules/tournament-rules-document'
import type { ExtractedTournamentRulesFamily } from '../rules-document-family.ts'

const GENERATED_HEADER = '// Generated by pnpm rules:generate. Do not edit.\n\n'

type RuntimeArtifact = { version: string; document: TournamentRulesDocument }

export type PreparedTournamentRules = {
	artifacts: Map<string, string>
	transcripts: Map<string, string>
	summary: { current: string; versions: number; transcripts: number }
}

function documentExportName(version: string): string {
	return `PDF_TOURNAMENT_RULES_${version.replaceAll('-', '_')}`
}

function versionFilename(version: string): string {
	return `v${version}.ts`
}

function serializeRuntimeVersion(document: TournamentRulesDocument): string {
	return `${GENERATED_HEADER}import type { TournamentRulesDocument } from '@/lib/rules/tournament-rules-document'\n\n// oxfmt-ignore\nexport const ${documentExportName(document.version)}: TournamentRulesDocument = ${JSON.stringify(document, null, 2)}\n`
}

function serializeRuntimeIndex(artifacts: RuntimeArtifact[], current: string): string {
	const imports = artifacts
		.map(
			({ version }) =>
				`import { ${documentExportName(version)} } from '@/generated/tournament-rules/v${version}'`,
		)
		.join('\n')
	const documentEntries = artifacts
		.map(({ version }) => `\t${JSON.stringify(version)}: ${documentExportName(version)},`)
		.join('\n')

	return `${GENERATED_HEADER}${imports}\nimport type { TournamentRulesDocument } from '@/lib/rules/tournament-rules-document'\n\nexport const CURRENT_PDF_TOURNAMENT_RULES_VERSION = ${JSON.stringify(current)}\n\nexport const PDF_TOURNAMENT_RULES_DOCUMENTS: Record<string, TournamentRulesDocument> = {\n${documentEntries}\n}\n`
}

export function prepareTournamentRulesArtifacts(
	extracted: ExtractedTournamentRulesFamily,
): PreparedTournamentRules {
	const documents: RuntimeArtifact[] = []
	const artifacts = new Map<string, string>()
	const transcripts = new Map<string, string>()

	for (const {
		registeredVersion: { version },
		document,
		transcript,
	} of extracted.versions) {
		documents.push({ version, document })
		artifacts.set(versionFilename(version), serializeRuntimeVersion(document))
		transcripts.set(`Tournament-Rules-${version}.txt`, transcript)
	}

	const current = extracted.currentVersion.registeredVersion.version
	artifacts.set('index.ts', serializeRuntimeIndex(documents, current))
	return {
		artifacts,
		transcripts,
		summary: {
			current,
			versions: documents.length,
			transcripts: transcripts.size,
		},
	}
}
